### PR TITLE
Merge with Debian version 1.4.1-5

### PR DESCRIPTION
**Pull request by ermshiperete**
This is necessary to be able to install our patched version on Groovy. This change also applies the patches (that Debian has in the form of patches) directly to the source tree.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
I don't understand the presence of the patch files but I guess everything else is pretty minimal.

**Comment by ermshiperete** [comment]
The patch files are part of the way Debian decided to do their packaging: the source code repo and the repo with the Debian packaging metadata are two separate repos. Debian only maintains the latter one. During a package build the latest release of the source code of the upstream repo gets imported. If Debian has additional fixes or changes that they want to make to the upstream source code, they store those changes in the form of patch files that get applied to the source tree during the package build.

In our fork we decided to merge the two repos, which makes it easier to handle. If Debian has patches we import them into our repo.

But I guess I forgot to delete the two Debian patch files (which doesn't hurt the packaging because I deleted the `series` file, but it will be confusing in the future...).

**Comment by mcdurdin** [comment]
> But I guess I forgot to delete the two Debian patch files (which doesn't hurt the packaging because I deleted the `series` file, but it will be confusing in the future...).

Do you need to do this work now?

**Comment by ermshiperete** [comment]
> Do you need to do this work now?

https://github.com/keymanapp/onboard-keyman/pull/4

**Pull request merged**
